### ISSUE TITLE
STL files should be simplified 

### ISSUE THREAD

**Issue by iron76** [kzts/athletebot#2]
At present some STL files are quite big (around 1 mega). For this reason inserting the Athletebot in the simulation takes some time. STL should be simplified by reducing the number of triangles and nodes.

**Comment by traversaro** [comment]
You can use [`meshlab`](http://meshlab.sourceforge.net/) for perform this kind of simplifications  .

**Comment by iron76** [comment]
Does it have a command-line interface?

**Comment by traversaro** [comment]
Yes, the `meshlabserver`command.

**Comment by iron76** [comment]
@traversaro thanks!
